auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User 
from passlib.hash import bcrypt
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)

ACCESS = {
    'guest': 0,
    'user': 1,
    'admin': 2
}
@auth.route('/login', methods=['GET', 'POST'])
def login():
    print("ssss")
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        #
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password) and user.access == 1 :
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            elif check_password_hash(user.password, password) and user.access == 0:
                flash('your account is not activatied, try again.', category='error')
            elif check_password_hash(user.password, password) and user.access==2  :
                login_user(user, remember=True)
                return redirect(url_for('views.admin'))
            else :
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))



@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        last_name = request.form.get('lastName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, last_name=last_name ,  password=generate_password_hash(
                password1, method='sha256')  )
            db.session.add(new_user)
            db.session.commit()
            flash('Account created! wait for authorization', category='success')

    return render_template("sign_up.html", user=current_user)

views.py
from flask import Blueprint, render_template, request, flash
from flask_login import login_required, current_user
from .models import  User, ACCESS, Patient, Donor, Transplantation , MatchingHistories
from flask import  render_template, flash, redirect, url_for, request
from flask_login import current_user,  login_required
from . import db  #means from __init__.py import db
from functools import wraps
from sqlalchemy import or_, func, desc
from .model import matching_result
import datetime

views = Blueprint('views', __name__)

### custom wrap to determine access level ###
def requires_access_level(access_level):
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            if not current_user.is_authenticated: #the user is not logged in
                return redirect(url_for('login'))
            #user = User.query.filter_by(id=current_user.id).first()
            if not current_user.allowed(access_level):
                flash('You do not have access to this resource.', 'Error')
                return redirect(url_for('auth.login'))
            return f(*args, **kwargs)
        return decorated_function
    return decorator


@views.route('/home', methods=['GET','POST'])
@requires_access_level(ACCESS['user'])
@login_required
def home():
    user_id = current_user.id
    unique_combinations = MatchingHistories.query.with_entities(
        MatchingHistories.id, MatchingHistories.DonorID, MatchingHistories.DateOfTransplantation
    ).filter_by(UserID=user_id).distinct().order_by(desc(MatchingHistories.id))
    if request.method == 'POST':
        donorID = request.form.get('donorID')
        return redirect(url_for('views.mathcing', donorID=donorID))
    return render_template("index.html", unique_combinations= unique_combinations)



@views.route('/admin')
@requires_access_level(ACCESS['admin'])
def admin():
    users = User.query.filter(or_(User.access == 0, User.access == 1)).all()
    return render_template("users.html", users=users)

@views.route("/update_activation/<int:user_id>/<int:activated>", methods=["GET"])
def update_activation(user_id, activated):
    user = User.query.get(user_id)
    if user.access == 0:
        user.access = 1
    else:
        user.access = 0
    db.session.commit()
    return "OK"

@views.route("/delete_user/<int:user_id>", methods=["POST"])
@requires_access_level(ACCESS['admin'])
def delete_user(user_id):
    user = User.query.get(user_id)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("views.admin"))


'''--------------------------------------------------------------------------------------------------------'''
'''------------------------------------------------DONOR---------------------------------------------------'''
'''--------------------------------------------------------------------------------------------------------'''




@views.route('/donor')
@requires_access_level(ACCESS['user'])
@login_required
def donor():
    donors = Donor.query.all()
    return render_template("Donor.html",donors = donors )


@views.route('/donor_search', methods=['POST'])
@requires_access_level(ACCESS['user'])
@login_required
def donor_search():
    search_query = request.form['searchQuery']
    donors = Donor.query.filter(Donor.DonorID.like(f"{search_query}%")).all()
    return render_template("Donor.html", donors=donors)


@views.route('/donor/<int:donorID>', methods=['GET','POST'])
@requires_access_level(ACCESS['user'])
@login_required
def view_donor(donorID):
    donor = Donor.query.filter_by(DonorID=donorID).first_or_404()
    return render_template("View-Donor.html", donor=donor)




@views.route('/donor/add_donor', methods=['GET','POST'])
@requires_access_level(ACCESS['user'])
@login_required
def add_donor():
    if request.method == 'POST':
        DonorID = request.form.get('donorID')
        donorA1 = request.form.get('donorA1')
        donorA2 = request.form.get('donorA2')
        donorB1 = request.form.get('donorB1')
        donorB2 = request.form.get('donorB2')
        donorC1 = request.form.get('donorC1')
        donorC2 = request.form.get('donorC2')
        donorDRB1 = request.form.get('donorDRB1')
        donorDRB2 = request.form.get('donorDRB2')
        donorDQA1 = request.form.get('donorDQA1')
        donorDQA2 = request.form.get('donorDQA2')
        donorDQB1 = request.form.get('donorDQB1')
        donorDQB2 = request.form.get('donorDQB2')
        input_status = request.form.get('inputStatus')
        BloodGroup = request.form.get('bloodGroup')
        date_of_birth = request.form.get('inputDate')
        isAvailable = True if input_status == "option1" else False
        donor = Donor.query.filter_by(DonorID=DonorID).first()
        if donor is None :
            new_donor = Donor(DonorID=DonorID,A1= donorA1, A2= donorA2, B1 = donorB1,B2= donorB2, C1 = donorC1, C2  = donorC2,
                            DQA1 = donorDQA1, DQA2= donorDQA2, DQB1= donorDQB1, DQB2= donorDQB2, DRB1= donorDRB1, DRB2= donorDRB2 ,
                            isAvailable = isAvailable, BloodGroup= BloodGroup, DateOfBirth= date_of_birth )
            db.session.add(new_donor)
            db.session.commit()
            flash('The donor has been added successfull!', 'success')
            return redirect(url_for('views.donor'))
        else :
            flash('The donor ID already exists!', 'error')

        
    return render_template("Add-Donor.html")


@views.route("/delete_donor/<int:donorID>", methods=["POST"])
@requires_access_level(ACCESS['user'])
def delete_donor(donorID):
    donor = Donor.query.filter_by(DonorID=donorID).first_or_404()
    if donor is not None:
        db.session.delete(donor)
        db.session.commit()
    return redirect(url_for("views.donor"))




@views.route('/Match/<int:donorID>')
@requires_access_level(ACCESS['user'])
@login_required
def mathcing(donorID):
    #get donor 
    donor = Donor.query.filter_by(DonorID=donorID).first()
    if donor is None:
        flash('no donor with this id number!', 'error')
        return redirect(url_for('views.home'))
    else :
        #retive patient 
        patients = Patient.query.filter_by(isPatientOnWaitingList=True)
        #call the intelligent model and return result 
        results ,ranking = matching_result(patients, donor) # the AI model 
        ranking = dict(sorted(ranking.items(), key=lambda x: x[1], reverse=True)) #sort decedning
        #store the result 
        store_histoy(donorID, results, ranking)
    return render_template("MatchResult.html", results = results, ranking=ranking , donor= donor)


@views.route('/Matching/<int:donorid>/<int:id>')
@requires_access_level(ACCESS['user'])
@login_required
def old_mathcing(donorid, id):
    donor = Donor.query.filter_by(DonorID=donorid).first_or_404()
    matching_histories = MatchingHistories.query.filter_by(DonorID=donorid, id=id).all()
    return render_template("old_matching_result.html", matching_histories=matching_histories, donor=donor)


@views.route('/delete_Matching_History/<int:donorid>/<int:id>')
@requires_access_level(ACCESS['user'])
@login_required
def delete_History(donorid, id):
    matching_histories = MatchingHistories.query.filter_by(DonorID=donorid, id=id).all()
    for matching_history in matching_histories:
        db.session.delete(matching_history)
    db.session.commit()
    return redirect(url_for('views.home'))




@views.route("/modify_Donor/<int:donorID>", methods=['GET', 'POST'])
@requires_access_level(ACCESS['user'])
def modify_Donor(donorID):
    donor = Donor.query.filter_by(DonorID=donorID).first_or_404()
    if request.method == 'POST':
        if request.form.get('patinetA1') != "" :
            donor.A1 = request.form.get('patinetA1')
        if request.form.get('patinetA2') != "" :
            donor.A2 = request.form.get('patinetA2')
            
        if request.form.get('patinetB1') != "" :
            donor.B1 = request.form.get('patinetB1')
        if request.form.get('patinetB2') !=  "" :
            donor.B2 = request.form.get('patinetB2')

        if request.form.get('patinetC1') !=  "" :
            donor.C1 = request.form.get('patinetC1')
        if request.form.get('patinetC2') !=  "" :
            donor.C2 = request.form.get('patinetC2')

        if request.form.get('patinetDRB1') !=  "" :
            donor.DRB1 = request.form.get('patinetDRB1')
        if request.form.get('patinetDRB2') !=  "" :
            donor.DRB2 = request.form.get('patinetDRB2')

        if request.form.get('patinetDQA1') != "" :
            donor.DQA1 = request.form.get('patinetDQA1')
        if request.form.get('patinetDQA2') != "" :
            donor.DQA2 = request.form.get('patinetDQA2')

        if request.form.get('patinetDQB1') != "" :
            donor.DQB1 = request.form.get('patinetDQB1')
        if request.form.get('patinetDQB2') != "" :
            donor.DQB2 = request.form.get('patinetDQB2')
       
        input_status = request.form.get('inputStatus')
        print(input_status)
        donor.isAvailable = True if input_status == "option1" or input_status == "Active"  else False
        donor.BloodGroup = request.form.get('bloodGroup')
        donor.DateOfBirth = request.form.get('inputDate')
       
        db.session.commit()
        flash('Donor updated successfully!', 'success')
        return redirect(url_for('views.view_donor', donorID=donor.DonorID))
    return render_template("Modify-Donor.html", donor=donor)


'''--------------------------------------------------------------------------------------------------------'''
'''-------------------------------------------TRANSPLANTATION----------------------------------------------'''
'''--------------------------------------------------------------------------------------------------------'''

@views.route('/transplantation')
@requires_access_level(ACCESS['user'])
@login_required
def transplantation():
    Transplantations = Transplantation.query.all() 

templates/Modify-transplantation.html
{% extends "base_transplantation.html" %} 
{% block title %}Transplantation{% endblock %} 
{% block content %}



  <section class="section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12">

          <div class="card p-4">
            <h5 class="card-title mb-4">Transplantation Information</h5>
            
            <form method="POST">
              

              <div class="row mb-3">
                <label  class="col-sm-2 col-form-label">Donor ID</label>
                <div class="col-sm-3">
                  <a href="{{ url_for('views.view_donor', donorID=transplantation.DonorID) }}">
                    {{ transplantation.DonorID }}
                  </a>
                </div>
              </div>

              <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Patient ID</label>
                <div class="col-sm-3">
                  <a href="{{ url_for('views.view_patient', PatientID=transplantation.PatientID) }}">
                    {{ transplantation.PatientID }}
                  </a>
                </div>
              </div>

              <div class="row mb-3">
                <label for="inputDate" class="col-sm-3 col-form-label">Date of Transplantation</label>
                <div class="col-sm-3">
                  <input type="date" name="DateOfTransplantation" class="form-control" value="{{ transplantation.DateOfTransplantation }}">
                </div>
              </div>

              <div class="row mb-3">
                <label for="inputPassword" class="col-sm-2 col-form-label">Complications</label>
                <div class="col-sm-4">
                  <textarea name="complications" class="form-control">{{ transplantation.complications }}</textarea>
                </div>
              </div>

              <div class="text-end">
                <button type="submit" class="btn btn-primary">Save</button>
              </div>

            </form>

          </div>
        </div>
      </div>
    </div>
  </section>



{% endblock %}

templates/View-Donor.html
{% extends "donor_base.html" %} {% block title %}Login{% endblock %} {% block content
    %}




        <section class="section">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-12">

                        <div class="card p-4">
                            
                            

                            <h5 class="card-title mb-4">Donor</h5>
                            <h5 class="card-title mb-4">Information</h5>

                            <div class="row mb-5">
                                <div class="col-md-4 col-sm-12 label" style="font-weight: bold;">Donor ID: </div>
                                <div class="col-md-8 col-sm-12">{{donor.DonorID}}</div>


                                <div class="col-md-4 col-sm-12 label" style="font-weight: bold;">Status: </div>
                                <div class="col-md-8 col-sm-12">

                                    {% if donor.isAvailable %}
                                    <span class="badge bg-success">Active</span>
                                    {% else %}
                                    <span class="badge bg-secondary">transplanted</span>

                                    {% endif %}
                                </div>


                                <div class="col-md-4 col-sm-12 label" style="font-weight: bold;">Date Of Birth:</div>
                                <div class="col-md-8 col-sm-12">{{donor.DateOfBirth}}</div>

                                <div class="col-md-4 col-sm-12 label" style="font-weight: bold;">Blood Group: </div>
                                <div class="col-md-8 col-sm-12">{{donor.BloodGroup}}</div>

                                <div class="col-md-4 col-sm-12 label" style="font-weight: bold;"> HLA </div>
                                <div class="col-md-8 col-sm-12"></div>

                                <div class="col-md-4 col-sm-12 label">A: </div>
                                <div class="col-md-8 col-sm-12">{{donor.A1}},{{donor.A2}}</div>


                                <div class="col-md-4 col-sm-12 label">B: </div>
                                <div class="col-md-8 col-sm-12">{{donor.B1}},{{donor.B2}}</div>

                                <div class="col-md-4 col-sm-12 label">C: </div>
                                <div class="col-md-8 col-sm-12">{{donor.C1}},{{donor.C2}}</div>


                                <div class="col-md-4 col-sm-12 label">DRB1: </div>
                                <div class="col-md-8 col-sm-12">{{donor.DRB1}},{{donor.DRB2}}</div>


                                <div class="col-md-4 col-sm-12 label">DQA1: </div>
                                <div class="col-md-8 col-sm-12">{{donor.DQA1}},{{donor.DQA2}}</div>

                                <div class="col-md-4 col-sm-12 label">DQB1: </div>
                                <div class="col-md-8 col-sm-12">{{donor.DQB1}},{{donor.DQB2}}</div>

                                <div class="text-end">

                                  <a href="{{ url_for('views.modify_Donor', donorID=donor.DonorID) }}">
                                        <button type="submit" class="btn btn-primary me-2">Modify</button>
                                    </a>


                                    <button class="btn btn-primary w-60" onclick="deleteDonor('{{ donor.DonorID }}')">Delete</button>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
        </section>


   

    {% endblock %}
    <!-- ======= Footer ======= 
  <footer id="footer" class="footer">
    
  </footer> End Footer -->


templates/View-Transplantation.html
{% extends "base_transplantation.html" %} {% block title %}Login{% endblock %} {% block content
%}




  <section class="section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12">

          <div class="card p-4">
            <h5 class="card-title mb-4">Transplantation</h5>
            <h5 class="card-title mb-4">Information</h5>

            <div class="row mb-5">
              <div class="col-md-4 col-sm-12 label">Donor ID</div>
              <div class="col-md-8 col-sm-12"><a
                  href="{{ url_for('views.view_donor', donorID=transplantation.DonorID) }}">{{transplantation.DonorID}}</a>
              </div>
            </div>

            <div class="row mb-5">
              <div class="col-md-4 col-sm-12 label">Patient ID</div>
              <div class="col-md-8 col-sm-12"><a
                  href="{{ url_for('views.view_patient', PatientID=transplantation.PatientID) }}">{{transplantation.PatientID}}</a>
              </div>
            </div>

            <div class="row mb-4">
              <div class="col-md-4 col-sm-12 label">Date Of Transplantation</div>
              <div class="col-md-8 col-sm-12">{{transplantation.DateOfTransplantation}}</div>
            </div>

            <div class="row mb-4">
              <div class="col-md-4 col-sm-6 label">Complications</div>
              <div class="col-md-4 col-sm-6">
                {% if transplantation.complications is none %}
                     None 
                {% else %}
                {{ transplantation.complications }}
                {% endif %}

              </div>
            </div>

            <div class="text-end">

              <a href="{{ url_for('views.modify_Transplantation', TransplantationID = transplantation.id) }}">
                <button type="submit" class="btn btn-primary me-2">Modify</button>
              </a>


              <button class="btn btn-primary w-60"
              onclick="deleteTransplantation('{{ transplantation.id }}')">Delete</button>
            </div>

          </div>
        </div>
      </div>
    </div>
  </section>




{% endblock %}

templates/base_transplantation.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Nephron - Transplantation</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">


    <link href="{{url_for('static',filename = 'vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static',filename = 'vendor/quill/quill.bubble.css')}}" rel="stylesheet">
    <link href="{{url_for('static',filename = 'vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}">




    <!-- Template Main CSS File -->
    <link href="{{url_for('static',filename = 'css/style.css')}}" rel="stylesheet">


</head>



<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">
        <div class="d-flex align-items-center justify-content-between">
            <a href="index.html" class="logo d-flex align-items-center">
                <img src="{{url_for('static',filename = '/img/logo.png')}}" alt="">
                <span class="d-none d-lg-block">Nephron</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->

        <div class="search-bar">
            <form class="search-form d-flex align-items-center" method="POST" action="{{ url_for('views.search_transplantation') }}">
                <input type="text" name="searchQuery" id="searchQuery" placeholder="Search" title="Enter patient id">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div>
        

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">
                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li><!-- End Search Icon-->

    </header><!-- End Header -->

    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">
        <ul class="sidebar-nav" id="sidebar-nav">
            <li class="nav-item">
                <a class="nav-link collapsed" href="{{ url_for('views.home')}}">
                    <i class="bi bi-percent"></i>
                    <span>Find Matching</span>
                </a>
            </li><!-- End Dashboard Nav -->
            <li class="nav-item">
                <a class="nav-link " href="{{ url_for('views.transplantation')}}">
                    <i class="bi bi-people-fill"></i>
                    <span>Transplantation</span>
                </a>
            </li><!-- End Dashboard Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{{ url_for('views.patient')}}">
                    <i class="bi bi-person-lines-fill"></i>
                    <span>Patient</span>
                </a>
            </li><!-- End Dashboard Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{{ url_for('views.donor')}}">
                    <i class="bi bi-person-lines-fill"></i>
                    <span>Donor</span>
                </a>
            </li><!-- End Dashboard Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed"href="{{url_for('auth.logout')}}">
                    <i class="bi bi-box-arrow-right"></i>
                    <span>Log-out</span>
                </a>
            </li><!-- End Dashboard Nav -->
        </ul>
    </aside><!-- End Sidebar-->



    <main id="main" class="main">


        {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == 'error' %}
                <div class="alert alert-danger alter-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" onclick="removeAlert(this)">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% else %}
                <div class="alert alert-success alter-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" onclick="removeAlert(this)">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}


        {% block content %} {% endblock %}
    </main><!-- End #main -->

    <!-- ======= Footer ======= 
  <footer id="footer" class="footer">
    
  </footer> End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- ======= Footer ======= 
<footer id="footer" class="footer">

</footer> End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <script src="{{ url_for('static', filename='js/main.js') }}"></script>

    <script src="{{url_for('static',filename = 'js/index.js')}}"></script>

    <script>
        function deleteTransplantation(transplantationId) {
            if (confirm("Are you sure you want to delete this transplantation?")) {
                var url = "/delete_Transplantation/" + transplantationId;
                var xhr = new XMLHttpRequest();
                xhr.open("POST", url, true);
                xhr.onload = function () {
                    if (xhr.status == 200) {
                        window.location.href = "{{ url_for('views.transplantation') }}";
                    }
                };
                xhr.send();
            }
        }
    </script>
     <script>
        function removeAlert(element) {
            // Get the parent element (the alert div) and remove it
            var alertElement = element.parentNode;
            alertElement.remove();
        }
    </script>



</body>

templates/index.html
{% extends "sidebar.html" %}
{% block title %}index{% endblock %}
{% block content %}

<section class="section">

  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Find Matching</h5>
          <!-- Horizontal Form -->
          <!-- input form -->
          <form method="POST">
            <div class="text-center">
              <div class="row mb-3">
                <label for="inputText" class="col-sm-2 col-form-label">Enter Donor ID</label>
                <div class="col-sm-3"> <!-- adjust column width here -->
                  <input type="text" name="donorID" class="form-control" id="donorID" required>
                </div>
                <div class="col-sm-2">
                  <button type="submit" class="btn btn-primary px-4">Match</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Matching History</h5>
         
        
           <table class="table">
            <thead>
              <tr>
                <th scope="col">Donor ID</th>
                <th scope="col">Date</th>
              </tr>
            </thead>
            <tbody>

              {% for i in unique_combinations %}

              <tr>
                
                <td>{{ i.DonorID }}</td>
                <td>{{ i.DateOfTransplantation.strftime('%H:%M:%S') }}</td>
              
              
                <td>
                  <a href="{{ url_for( 'views.old_mathcing', donorid=i.DonorID , id = i.id )}}">
                    <button type="button" class="btn btn-primary btn-sm">View</button>
                  </a>
                 
                </td>
                <td>
                  <a href="{{ url_for( 'views.delete_History', donorid=i.DonorID , id = i.id )}}">
                    <button type="button" class="btn btn-primary btn-sm">Delete</button>
                  </a>
                 
                </td>
              </tr>

              {% endfor %}

            </tbody>

          </table>
           
       
          <!-- Horizontal Form -->
          <!-- input form -->

        </div>
      </div>
    </div>
  </div>

</section>
{% endblock %}

templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<div class="card mb-3">


  <div class="card-body">

    <form class="row g-3 needs-validation" method="POST">


      <div class="pt-4 pb-2">
        <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
        <p class="text-center small">Enter your username & password to login</p>
      </div>

      <div class="col-12">
        <label for="yourUsername" class="form-label">Email</label>
        <div class="input-group has-validation">
          <input type="text" name="email" class="form-control" id="email" placeholder="Email" required>

          <div class="invalid-feedback">Please enter your Email</div>
        </div>
      </div>

      <div class="col-12">
        <label for="yourPassword" class="form-label">Password</label>
        <input type="password" name="password" class="form-control" id="password" placeholder="password" required>
        <div class="invalid-feedback">Please enter your password!</div>
      </div>

      <div class="col-12">

      </div>
      <div class="col-12">
        <button class="btn btn-primary w-100" type="submit">Login</button>
      </div>
      <div class="col-12">
        <p class="small mb-0">Don't have account? <a href="{{url_for('auth.sign_up')}}">Create an account</a></p>
      </div>
    </form>
  </div>
</div>

{% endblock %}